#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <glm/glm.hpp>

namespace Arche {
    namespace Render {

        /**
         * @brief Platform-agnostic 3D mesh geometry container.
         * 
         * Mesh stores vertex data (positions, normals, UVs) and optional index
         * data for efficient rendering. The rendering backend uploads this data
         * to the GPU and caches the VAO/VBO/IBO handles.
         * 
         * Meshes are typically loaded from files or procedurally generated by
         * MeshGenerator, then stored in the ResourceRegistry for reuse.
         */
        class Mesh {
          public:
            /**
             * @brief Primitive topology types.
             */
            enum class Primitive { 
                Points,    ///< Each vertex is a point
                Lines,     ///< Pairs of vertices form lines
                Triangles  ///< Triplets of vertices form triangles
            };

            /**
             * @brief Vertex data structure.
             * 
             * Contains all per-vertex attributes needed for rendering.
             */
            struct Vertex {
                glm::vec3 position{};  ///< Vertex position in model space
                glm::vec3 normal{};    ///< Surface normal vector (normalized)
                glm::vec2 uv{};        ///< Texture coordinates
            };

            /**
             * @brief Default constructor for empty mesh.
             */
            Mesh() = default;
            
            /**
             * @brief Construct a named empty mesh.
             * @param name Mesh identifier
             */
            explicit Mesh(std::string name) : m_name(std::move(name)) {}

            /**
             * @brief Get the mesh's name.
             * @return Mesh identifier
             */
            const std::string& getName() const { return m_name; }
            
            /**
             * @brief Set the mesh's name.
             * @param n New mesh identifier
             */
            void setName(std::string n) { m_name = std::move(n); }

            /**
             * @brief Set the primitive topology.
             * @param p Primitive type (points, lines, or triangles)
             */
            void setPrimitive(Primitive p) { m_primitive = p; }
            
            /**
             * @brief Get the primitive topology.
             * @return Current primitive type
             */
            Primitive getPrimitive() const { return m_primitive; }

            /**
             * @brief Get mutable access to vertices.
             * @return Reference to vertex array
             */
            std::vector<Vertex>& vertices() { return m_vertices; }
            
            /**
             * @brief Get const access to vertices.
             * @return Const reference to vertex array
             */
            const std::vector<Vertex>& vertices() const { return m_vertices; }

            /**
             * @brief Get mutable access to indices.
             * @return Reference to index array
             */
            std::vector<std::uint32_t>& indices() { return m_indices; }
            
            /**
             * @brief Get const access to indices.
             * @return Const reference to index array
             */
            const std::vector<std::uint32_t>& indices() const { return m_indices; }

            /**
             * @brief Check if mesh uses indexed rendering.
             * @return true if indices are present, false otherwise
             */
            bool hasIndices() const { return !m_indices.empty(); }

            /**
             * @brief Clear all vertex and index data.
             */
            void clear() { m_vertices.clear(); m_indices.clear(); }
            
            /**
             * @brief Get number of vertices.
             * @return Vertex count
             */
            size_t vertexCount() const { return m_vertices.size(); }
            
            /**
             * @brief Get number of indices.
             * @return Index count
             */
            size_t indexCount() const { return m_indices.size(); }

          private:
            std::string m_name;                         ///< Mesh identifier
            Primitive m_primitive{Primitive::Triangles};///< Topology type
            std::vector<Vertex> m_vertices;             ///< Vertex data
            std::vector<std::uint32_t> m_indices;       ///< Index data (optional)
        };

    } // namespace Render
} // namespace Arche